version: "3"

services:
  frontend:
    image: node:17-alpine3.14
    ports:
      - '3000:3000'
    volumes:
      - ../frontend:/srv/react-docker
    working_dir: /srv/react-docker
    command: ["yarn", "start"]
  
  backend:
    image: hyperf/hyperf:8.0-alpine-v3.14-swoole
    entrypoint: ["composer", "dev"]
    stdin_open: true
    tty: true
    scale: 3
    expose:
      - "9501"
      - "9502"
    volumes:
      - "../backend/:/data/project"
    working_dir: /data/project
    networks:
      - chat-redis
    links:
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "4000:4000"
      - "9502:9502"
    networks:
      - chat-redis
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - chat-redis
networks:
  chat-redis:
    driver: bridge